//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoFinal.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alumnos
    {
        public Alumnos()
        {
            this.Inscripciones = new HashSet<Inscripciones>();
        }
    
        public int ID { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Direccion { get; set; }
        public string Telefono { get; set; }
        public string Padre { get; set; }
        public string Madre { get; set; }
        public string Tutor { get; set; }
        public string Enfermedades { get; set; }
        public string Observaciones { get; set; }
        public byte[] Foto { get; set; }
        public bool Habilitado { get; set; }
        public string Dni { get; set; }
    
        public virtual ICollection<Inscripciones> Inscripciones { get; set; }
    }
}
