//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoFinal.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class AsignacionGrados
    {
        public int ID { get; set; }
        public int DocentesID { get; set; }
        public int DivisionesID { get; set; }
        public bool Habilitado { get; set; }
    
        public virtual Divisiones Divisiones { get; set; }
        public virtual Docentes Docentes { get; set; }
    }
}
