//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoFinal.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Institucion
    {
        public Institucion()
        {
            this.Directivos = new HashSet<Directivos>();
            this.Niveles = new HashSet<Niveles>();
        }
    
        public int ID { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public string CodigoMin { get; set; }
        public string Direccion { get; set; }
        public string Telefono { get; set; }
        public bool Habilitado { get; set; }
    
        public virtual ICollection<Directivos> Directivos { get; set; }
        public virtual ICollection<Niveles> Niveles { get; set; }
    }
}
