//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoFinal.Modelo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    using System.Collections.Generic;
    
    public partial class ProyectoEntities : DbContext
    {
        public ProyectoEntities()
            : base("name=ProyectoEntities6")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Alumnos> Alumnos { get; set; }
        public virtual DbSet<AñoLectivo> AñoLectivo { get; set; }
        public virtual DbSet<AsignacionGrados> AsignacionGrados { get; set; }
        public virtual DbSet<CondicionDocente> CondicionDocente { get; set; }
        public virtual DbSet<Directivos> Directivos { get; set; }
        public virtual DbSet<Divisiones> Divisiones { get; set; }
        public virtual DbSet<Docentes> Docentes { get; set; }
        public virtual DbSet<Grados> Grados { get; set; }
        public virtual DbSet<Inscripciones> Inscripciones { get; set; }
        public virtual DbSet<Institucion> Institucion { get; set; }
        public virtual DbSet<Niveles> Niveles { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Turnos> Turnos { get; set; }

        public virtual List<Asignaciondivisiondocente_Result> Asignaciondivisiondocente()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Asignaciondivisiondocente_Result>("Asignaciondivisiondocente").ToList();
        }

        public virtual List<Inscripcionesconsultalistado_Result> Inscripcionesconsultalistado()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Inscripcionesconsultalistado_Result>("Inscripcionesconsultalistado").ToList();
        }
    }
}
